name: Feature Request
description: File a feature request
labels: ["enhancement"]
body:
  - type: checkboxes
    attributes: 
      label: Prerequisites
      options:
        - label: I have searched for related issues in the [issues](https://github.com/zhongyang219/TrafficMonitor/issues) list.
          required: true
  - type: input
    attributes:
      label: Current TrafficMonitor Version
      description: "Right-click the TrafficMonitor tray icon, select `Help` → `About`."
    validations: 
      required: true
  - type: textarea
    attributes:   
      label: Describe the feature
      description: "For ease of management, please do not report multiple unrelated issues under the same issue."
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional Information
      description: "If you have other information to note, you can fill it in here."
